set -g mouse on

set-option -g status-position top 

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'macchiato' 

set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_status_icon_enable "yes"

set -g @catppuccin_icon_window_zoom " "
set -g @catppuccin_icon_window_last "null"
set -g @catppuccin_icon_window_current "null"
set -g @catppuccin_icon_window_mark "null"
set -g @catppuccin_icon_window_silent "null"
set -g @catppuccin_icon_window_activity "null"
set -g @catppuccin_icon_window_bell "null"

set -g @catppuccin_window_middle_separator "null"

set -g @catppuccin_window_default_fill "all"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory session"
set -g @catppuccin_maximized_text "null"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_directory_color "#8aadf4"
