# NVM autogenerated stuff.
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Custom stuff

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

alias c=clear
alias vim=nvim

eval "$(starship init zsh)"
