unbind C-b

set -g mouse on

set -g prefix C-x
bind C-x send-prefix

bind Q detach-client

bind v split-window -h
bind s split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
